---
- name: clone the repository mattermost
  ansible.builtin.git:
    repo: "https://github.com/mattermost/docker"
    dest: "{{ path }}"
    clone: yes
    update: yes

- name: create a directory volumes mattermost
  ansible.builtin.file:
    path: "{{ path }}/volumes/project/mattermost{{ item }}"
    state: directory
    recurse: yes
    owner: "2000"
    group: "2000"
    mode: "0755"
  loop: "{{ mattermost_volumes }}"
  ignore_errors: true

- name: create a directory volumes mattermost client plugins
  ansible.builtin.file:
    path: "{{ path }}/volumes/project/mattermost/client/plugins/"
    state: directory
    recurse: yes
    owner: "2000"
    group: "2000"
    mode: "0755"
  ignore_errors: true

- name: transfer env files
  ansible.builtin.template:
    src: env.j2
    dest: "{{ path }}/.env"

- name: project-compose up -d mattermost
  ansible.builtin.shell: "project-compose -f {{ path }}/project-compose.yml -f {{ path }}/project-compose.without-nginx.yml up -d"
  ignore_errors: true
